apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ssl-passthrough

  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.host.com
  rules:
    - host: app.host.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: secure-service-app
                port:
                  number: 443